- hosts: terraform-ansible
  tasks:
  - name: create a file
    copy:
      dest: /home/ubuntu/index.html
      content: "<h1>Make with terraform-ansible</h1>"
  - name: create a server
    shell: "nohup busybox httpd -f -p 8080 &"